" Example Vim configuration.
" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

call pathogen#infect()
Helptags

syntax enable                     " Turn on syntax highlighting.

set background=dark
colorscheme solarized

filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set t_Co=256

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set dir=$HOME/tmp                 " Keep swap files in one location

"indent settings
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent

set linespace=4

"vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

set laststatus=2

"Key mapping for textmate-like indentation
nmap <D-[> <<
nmap <D-]> >>
vmap <D-[> <gv
vmap <D-]> >gv

let mapleader = ','

inoremap jk <Esc>

nnoremap <silent><leader>/ :noh<cr>
nnoremap <silent><leader>r :redraw!<CR>

"close single buffer without closing split window
nnoremap <F4> :Kwbd<CR>

"reindent file
nnoremap <silent> <F8> mmgg=G'm^

"Enabling Zencoding
let g:user_zen_settings = {
      \  'php' : {
      \    'extends' : 'html',
      \    'filters' : 'c',
      \  },
      \  'xml' : {
      \    'extends' : 'html',
      \  },
      \  'haml' : {
      \    'extends' : 'html',
      \  },
      \  'erb' : {
      \    'extends' : 'html',
      \  },
      \}

" html indentation
let g:html_indent_inctags = "html,body,head,tbody"

let g:airline_enable_fugitive=1
let g:airline_powerline_fonts=1

let g:ctrlp_map = '<c-f>'
let g:ctrlp_root_markers = ['.ctrlp']

let g:mustache_abbreviations = 1

set exrc

" NERDTree setup
" Toggle NERDTree mappings
map <C-n> :NERDTreeToggle<CR>

function! CleverTab()
  if pumvisible()
    return "\<C-N>"
  endif
  if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
    return "\<Tab>"
  else
    return "\<C-N>"
  endif
endfunction

inoremap <Nul> <C-R>=CleverTab()<CR>

autocmd FileType javascript call RagtagInit()
